services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      APP_ENV: production
      GROQ_API_KEY: $GROQ_API_KEY
      PORT: 8080
    volumes:
      - sqlite_bp:/app/login-store.db
volumes:
  sqlite_bp:
